# Generated by Django 5.1.3 on 2024-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(max_length=20)),
                ('occupations', models.CharField(max_length=100)),
                ('digenations', models.CharField(max_length=200)),
            ],
        ),
    ]
