# Generated by Django 5.1.3 on 2024-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
